language: ruby
rvm:
  - 2.0.0
  - 1.9.3
before_script:
  - bundle exec rake db:create db:migrate db:test:prepare
  - testando isso aqui vai dar erro
script:
  - bundle exec rake

#whitelist
branches:
  only:
      - master
