language: ruby
rvm:
  - 2.0.0
  - 1.9.3
before_script:
  - bundle exec rake db:create db:migrate db:test:prepare
script:
  - bundle exec rake
after_script:
  - testando after

#whitelist
branches:
  only:
      - master
